spring.application.name=web-integrado-service

# Base de datos H2 en memoria para desarrollo
spring.datasource.url=jdbc:h2:mem:web_integrado_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Inicializacion SQL
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

cors.allowOrigins=http://localhost:4200
cors.allowMethods=GET,POST,PUT,DELETE
cors.allowHeaders=*
cors.exposedHeaders=Authorization
cors.maxAge=3600
cors.allowCredentials=true
cors.mapping=/**
