CREATE ALIAS IF NOT EXISTS DATE_FORMAT FOR "com.proyecto.integrador.util.H2Functions.dateFormat";

DROP TABLE IF EXISTS incidencia_evidencia;
DROP TABLE IF EXISTS incidencia_historial;
DROP TABLE IF EXISTS incidencia;
DROP TABLE IF EXISTS usuario_rol;
DROP TABLE IF EXISTS sla;
DROP TABLE IF EXISTS estado_incidencia;
DROP TABLE IF EXISTS prioridad;
DROP TABLE IF EXISTS severidad;
DROP TABLE IF EXISTS ubicacion;
DROP TABLE IF EXISTS categoria;
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS rol;

CREATE TABLE rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_rol PRIMARY KEY (id_rol),
    CONSTRAINT uk_rol_nombre UNIQUE (nombre)
);

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
    usuario VARCHAR(100) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_usuario UNIQUE (usuario),
    CONSTRAINT uk_usuario_correo UNIQUE (correo)
);

CREATE TABLE usuario_rol (
    id_usuario_rol INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INTEGER NOT NULL,
    id_rol INTEGER NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario_rol),
    CONSTRAINT uk_usuario_rol UNIQUE (id_usuario, id_rol),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (id_rol) REFERENCES rol (id_rol)
);

CREATE TABLE categoria (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria)
);

CREATE TABLE ubicacion (
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_ubicacion PRIMARY KEY (id_ubicacion)
);

CREATE TABLE severidad (
    id_severidad INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    nivel INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_severidad PRIMARY KEY (id_severidad),
    CONSTRAINT uk_severidad_nombre UNIQUE (nombre)
);

CREATE TABLE prioridad (
    id_prioridad INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    nivel INTEGER NOT NULL,
    puntaje_minimo INTEGER NOT NULL,
    puntaje_maximo INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_prioridad PRIMARY KEY (id_prioridad),
    CONSTRAINT uk_prioridad_nombre UNIQUE (nombre),
    CONSTRAINT ck_prioridad_rango CHECK (puntaje_minimo <= puntaje_maximo)
);

CREATE TABLE estado_incidencia (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_estado_incidencia PRIMARY KEY (id_estado),
    CONSTRAINT uk_estado_incidencia_nombre UNIQUE (nombre)
);

CREATE TABLE sla (
    id_sla INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_severidad INTEGER NOT NULL,
    minutos_resolucion INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_sla PRIMARY KEY (id_sla),
    CONSTRAINT fk_sla_severidad FOREIGN KEY (id_severidad) REFERENCES severidad (id_severidad)
);

CREATE TABLE incidencia (
    id_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(50) NOT NULL,
    id_reportante INTEGER NOT NULL,
    id_responsable INTEGER,
    id_categoria INTEGER NOT NULL,
    id_ubicacion INTEGER NOT NULL,
    id_severidad INTEGER,
    id_prioridad INTEGER,
    id_estado INTEGER NOT NULL,
    id_sla INTEGER,
    impacto INTEGER,
    urgencia INTEGER,
    reincidencia INTEGER,
    puntaje_prioridad INTEGER,
    titulo VARCHAR(200) NOT NULL,
    descripcion CLOB NOT NULL,
    fecha_registro TIMESTAMP NOT NULL,
    fecha_limite TIMESTAMP,
    fecha_resolucion TIMESTAMP,
    fecha_cierre TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_incidencia PRIMARY KEY (id_incidencia),
    CONSTRAINT uk_incidencia_codigo UNIQUE (codigo),
    CONSTRAINT ck_incidencia_impacto CHECK (impacto IS NULL OR impacto IN (1, 2, 3)),
    CONSTRAINT ck_incidencia_urgencia CHECK (urgencia IS NULL OR urgencia IN (1, 2, 3)),
    CONSTRAINT ck_incidencia_reincidencia CHECK (reincidencia IS NULL OR reincidencia IN (0, 1)),
    CONSTRAINT fk_incidencia_reportante FOREIGN KEY (id_reportante) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_incidencia_responsable FOREIGN KEY (id_responsable) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_incidencia_categoria FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria),
    CONSTRAINT fk_incidencia_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion),
    CONSTRAINT fk_incidencia_severidad FOREIGN KEY (id_severidad) REFERENCES severidad (id_severidad),
    CONSTRAINT fk_incidencia_prioridad FOREIGN KEY (id_prioridad) REFERENCES prioridad (id_prioridad),
    CONSTRAINT fk_incidencia_estado FOREIGN KEY (id_estado) REFERENCES estado_incidencia (id_estado),
    CONSTRAINT fk_incidencia_sla FOREIGN KEY (id_sla) REFERENCES sla (id_sla)
);

CREATE TABLE incidencia_historial (
    id_historial INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    tipo_evento VARCHAR(100) NOT NULL,
    valor_anterior VARCHAR(255),
    valor_nuevo VARCHAR(255),
    descripcion VARCHAR(500),
    fecha_evento TIMESTAMP NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_incidencia_historial PRIMARY KEY (id_historial),
    CONSTRAINT fk_historial_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencia (id_incidencia),
    CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
);

CREATE TABLE incidencia_evidencia (
    id_evidencia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    ruta_archivo VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    fecha_registro TIMESTAMP NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FEC_REG TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FEC_MOD TIMESTAMP,
    CONSTRAINT pk_incidencia_evidencia PRIMARY KEY (id_evidencia),
    CONSTRAINT fk_evidencia_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencia (id_incidencia),
    CONSTRAINT fk_evidencia_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
);
